#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/foxxdesk/rustdesk /usr/bin/rustdesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/foxxdesk.service ]; then
			rm /etc/systemd/system/foxxdesk.service /usr/lib/systemd/system/foxxdesk.service /usr/lib/systemd/user/foxxdesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/foxxdesk/files/systemd/foxxdesk.service /usr/lib/systemd/system/foxxdesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload foxxdesk.service: Unit foxxdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/foxxdesk.service:10: Executable path is not absolute: pkill -f "rustdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/foxxdesk.service
		fi
		systemctl daemon-reload
		systemctl enable rustdesk
		systemctl start rustdesk
	fi
fi
